# Use the official Ubuntu base image
FROM ubuntu:24.04

# Accept proxy settings as build arguments
# ARG HTTP_PROXY
# ARG HTTPS_PROXY
# ARG NO_PROXY

# Install necessary packages including sudo
RUN apt-get update && apt-get install -y \
    locales \
    file \
    tree \
    curl \
    wget \
    tar \
    subversion \
    git \
    unzip \
    gcc \
    python3 \
    python3-venv \
    sudo \
    software-properties-common \
    && apt-get clean


# Download and install the latest version of Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
    apt-get install -y nodejs

# Download and install the latest fish
RUN apt-add-repository ppa:fish-shell/release-3 && \
    apt update && \
    apt install -y fish

# Download and install the latest Neovim
RUN add-apt-repository ppa:neovim-ppa/stable && \
    apt-get update && \
    apt-get install -y neovim

# Set proxy settings as environment variables
ENV http_proxy=http://192.168.0.102:8123
ENV https_proxy=http://192.168.0.102:8123

# Install the latest fzf
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install

# Install the latest bat
RUN apt install -y bat

# Install the latest fd
RUN curl -L -o fd_latest_amd64.deb https://github.com/sharkdp/fd/releases/download/v10.1.0/fd_10.1.0_amd64.deb && \
    dpkg -i fd_latest_amd64.deb

# Install rg
RUN curl -LO https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
RUN dpkg -i ripgrep_14.1.0-1_amd64.deb

# locale config
RUN locale-gen en_US.UTF-8

# Create a new user 'lapis' and set up the home directory
RUN useradd -m -s /bin/bash lapis && \
    echo 'lapis ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Switch to the new user
USER lapis
WORKDIR /home/lapis

# Clone the Neovim configuration repository as the 'lapis' user
RUN git clone https://github.com/Lapiiiiiiiiis/kickstart.nvim.git "${XDG_CONFIG_HOME:-/home/lapis/.config}"/nvim

SHELL ["/bin/fish", "-c"]
RUN curl -L https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher && fisher install PatrickF1/fzf.fish && fisher install jethrokuan/z

# Set Neovim as the default editor
ENV EDITOR=nvim

# Define the entry point
ENTRYPOINT ["/bin/fish"]

